### ISSUE TITLE
ECONNREFUSED - Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by gki-atolcd** [ONLYOFFICE/onlyoffice-nextcloud#1043]
Hello, 

I can't get this connector to work, I've searched and found many topics concerning this error but no solution has yet solved this problem.

This is a dockerized nextcloud 30, with onlyoffice on the same network.
Onlyoffice is up and running, and I can access it using its internal IP address which I'm using in the connector admin page (the docker container name works as well)

But no matter what I try, I still get this message when I try to save the configuration:

“Error while downloading the document file to be converted.) (version 8.2.0.143)”
 
which in the Onlyoffice container logs correspond to:

“[2024-11-18T15:06:51.820] [ERROR] [localhost] [check_472350801] [userId] nodeJS - error downloadFile:url=http://nextcloud.localhost:8080/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.HO8yVThljmrKFAiXsGoWMtnWnjfNFj-idymye3GiplM;attempt=3;code:ECONNREFUSED;connect:null Error: connect ECONNREFUSED 127.0.0.1:8080
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)”

I've tried leaving the dropdown advanced settings closed/open, checking/unchecking the checkbox for certificates, changing the JWT header to "AuthorizationJwt" instead of the default "Autorization", manually fill in the advanced parameters, and finally disabling JWT, but nothing works.

Here is the relevant parts of my compose.yml
```yaml
  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./config:/var/www/html/config
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=nextcloud.localhost
    depends_on:
      - proxy
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8080:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - certs:/etc/nginx/certs:ro,z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - dhparam:/etc/nginx/dhparam:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    environment:
      - DEFAULT_HOST=nextcloud.localhost
    networks:
      - proxy-tier

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - SECURE_LINK_SECRET=secret
      - JWT_ENABLED=false # <- Latest test to see if the problem is because of JWT
      - JWT_SECRET=secret
      - JWT_HEADER=AuthorizationJwt
      - USE_UNAUTHORIZED_STORAGE=true
      - ALLOW_PRIVATE_IP_ADDRESS=true
    volumes:
      - ./onlyoffice/document_data:/var/www/onlyoffice/Data
      - ./onlyoffice/document_log:/var/log/onlyoffice
    networks:
      - proxy-tier
```

The proxy is based on nginxproxy/nginx-proxy:alpine

The documentserver-jwt-status.sh command give me:
```
Your JWT settings:
JWT enabled -  false
```
I deactivated it to rule out the possibility that it might cause the connection to fail, since it didn't work when enabled, but the error message is still the same

Any ideas?
