### ISSUE TITLE
GetConvertedUri on check error: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.

### ISSUE THREAD

**Issue by kohfuchs** [ONLYOFFICE/onlyoffice-nextcloud#126]
Hi, 
I'm trying to connect my nextcloud to onlyoffice, which runs in docker but i get the error mentioned above.

OS | Nextcloud | Docker
------------ | ------------- | -------------
Ubuntu Server 18.04. | 16.0.3 on Apache (bare metal) | 19.03.1, build 74b1e89 

I'm using the following `docker-compose.yml` to start the container.
```
version: '2.2'
services:
     onlyoffice:
       image: onlyoffice/documentserver:latest
       restart: always
       volumes:
         - /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
         - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
         - /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
         - /app/onlyoffice/DocumentServer/db:/var/lib/postgresql
       environment:
         - JWT_ENABLED=true
         - JWT_SECRET=mysecret
       ports:
         - '8000:80'
         - '4433:443'
```
certificates are made as mentioned in the documentation and stored in `/app/onlyoffice/DocumentServer/data/certs/`

Documentserver is running. (lokal ip)

![image](https://user-images.githubusercontent.com/39412739/63799852-36a43600-c90d-11e9-9332-e6e069fc095b.png)

I've added the following lines to my `config.php` from Nextcloud
```
'trusted_domains' => 
  array (
	0 => 'koh.cloud',
	1 => '192.168.1.10',
	2 => '127.0.0.1',
  ),
```

AND

```
'onlyoffice' =>
array (
    'verify_peer_off' => true,
    "jwt_secret" => "mysecret",
    "jwt_header" => "Authorization",
      ),

```

enter in nextcloud as follow

![image](https://user-images.githubusercontent.com/39412739/63800735-11182c00-c90f-11e9-8cd4-8cfc188ee4c4.png)

Still the same error.

![image](https://user-images.githubusercontent.com/39412739/63800620-d4e4cb80-c90e-11e9-9be7-43d9eec2051e.png)

Any idea, what I'm doing wrong?
