### ISSUE TITLE
Unknown error without any info/log to troubleshoot

### ISSUE THREAD

**Issue by arkanoid87** [ONLYOFFICE/onlyoffice-nextcloud#151]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Unknown error without any info

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
client > TLS terminator reverse proxy (traefik) > nextcloud (+ app) + documentserver
using traefik:latest, nextcloud:latest and onlyoffice/documentserver:latest in a docker-compose stack.
Stacks seems correctly configured: I successfully set all the urls (even http internal ones) in nextcloud app config and both nextcloud and documentserver public https endpoints are reachable.
Problem: open ANY document (tested newly created one and the xlsx you provide as example), tab opens, onlyoffice seems to load, then a misterious "unknown error" popup.

**What is the expected behavior?**
Documents opens correctly in new tab

**Did this work in previous versions of DocumentServer?**
Tested 5.3.0.243, same problem there

**DocumentServer version:**
5.4.1.39

**Operating System:**
Ubuntu server 18.04

**Browser version:**
Firefox 69.0.1

I've been searching for hints on how to debug the problem for hours unsuccessfully.
Been loooking into:
- browser js console
- traefik logs
- nextcloud logs
- documentserver logs

Also tried:
- disable CSP
- tail -f /var/log/onlyoffice/documentserver/**/*.log (no output here when triggering the problem)
- tail -f /var/www/html/data/nextcloud.log (no ouput here when triggering the problem)

More info:
- browser dev tools shows no network errors (code 200 everywhere)

![2019-10-10-002835_812x602_scrot](https://user-images.githubusercontent.com/1446586/66525198-04cde400-eaf5-11e9-9279-4a08424cc165.png)

It's issue ONLYOFFICE/DocumentServer#666 for a reason

**Comment by raph2i** [comment]
Hey guys, same issue here. Traefik 2 - nextcloud-17-apache - documentserver

**Comment by alexanderonlyoffice** [comment]
Hello @arkanoid87, it looks likes there is some problem with the functioning of the Document Server. 

Please check the Document Server by entering the address _https://documentserver_address/healthcheck/_ and send us the response you get in browser.

Enable extending logging for the Document Server: open /etc/onlyoffice/documentserver/log4js/production.json and replace the 'WARN' value with 'DEBUG' of the "level" parameter. Then restart all services of the Document Server with a command `supervisorctl restart all`. Then open ONLYOFFICE integration app settings page in Nextcloud and click on the 'Save' button. check the logs after that.

**Comment by samuel-p** [comment]
I have the same issue since I upgraded Traefik to v2. `/healthcheck/` returns `true`.

**Comment by derdrave** [comment]
Same here with traefik2(.0.4)

i changed logging to debug and did two things: First i went to the settings-page and saved my settings again and second i tried to open a document.. where the referenced error appears.

the nginx-log from location "/var/log/onlyoffice/documentserver/nginx.error.log" shows these errors:

`2019/11/04 10:09:05 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:05 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:05 [error] 710#710: *1 no live upstreams while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://docservice/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:05 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:05 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:06 [error] 710#710: *1 no live upstreams while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://docservice/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:06 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:06 [error] 710#710: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "office.yourserver.com"
2019/11/04 10:09:06 [error] 710#710: *1 no live upstreams while connecting to upstream, client: 172.18.0.2, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://docservice/welcome/", host: "office.yourserver.com"
`


when i set up onlyoffice and nextcloud dockers with an haproxy docker (official) i have no problems with my setups..

**Comment by derdrave** [comment]
i found a temporary solution by reconfiguring nginx inside the docker:

in file: /etc/nginx/includes/http-common.conf
i commented out this line:
```
proxy_set_header Connection $proxy_connection; 
-->
# proxy_set_header Connection $proxy_connection; 
```

and then i did:
`service restard nginx`  


Now i can start onlyoffice... but I'm still not sure if this bug is on traefik or onlyoffice side..

**Comment by Get-Smart1** [comment]
Thanks you for the temporary fix. 

I also looked hours for the solution 👍🏻

**Comment by senguendk** [comment]
> i found a temporary solution by reconfiguring nginx inside the docker:
> 
> in file: /etc/nginx/includes/http-common.conf
> i commented out this line (bottom of the file):
> 
> ```
> proxy_set_header Connection $proxy_connection; 
> -->
> # proxy_set_header Connection $proxy_connection; 
> ```
> 
> and then i did:
> `service restart nginx`
> 
> Now i can open onlyoffice-documents from nextcloud... but I'm still not sure if this bug is on traefik or onlyoffice side..

I can confirm that this workaround works.

**Comment by Maurotb** [comment]
> I have the same issue since I upgraded Traefik to v2. `/healthcheck/` returns `true`.

Same problem when update to traefik 2
Workarround # proxy_set_header Connection $proxy_connection;  work for me

**Comment by LinneyS** [comment]
See the `healthcheck` status.
When setting up the proxy, you must transfer the _protocol_, _host_ and _port_ to the documentserver.
Look for errors while saving connection settings.
Enable full docuemtnserver and nextcloud logs and see error messages.

@arkanoid87 
Could you please specify if the problem recurs?

**Comment by calvinbui** [comment]
For those on Traefik 2, I was able to fix the problem with these labels/headers:

```yaml
traefik.http.routers.onlyoffice-secure.entrypoints: "web-secure"
traefik.http.routers.collabora-secure.tls: "true"
traefik.http.routers.collabora-secure.tls.certresolver: letsencrypt
traefik.http.services.onlyoffice.loadbalancer.server.port: "80"
traefik.http.routers.onlyoffice-secure.middlewares: "onlyoffice-sslheaders"
traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto: "https"
```

![image](https://user-images.githubusercontent.com/3604363/72221205-7f067c80-35ac-11ea-8d10-10b7611c225e.png)


Similarly if you're having CORS problems, use the CORS header as well

```yaml
traefik.http.routers.onlyoffice-secure.middlewares: "onlyoffice-sslheaders, onlyoffice-cors"
traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto: "https"
traefik.http.middlewares.onlyoffice-cors.headers.accessControlAllowOrigin: "*"
```

**Comment by wcdgit** [comment]
> 
> Similarly if you're having CORS problems, use the CORS header as well
> 
> ```yaml
> traefik.http.routers.onlyoffice-secure.middlewares: "onlyoffice-sslheaders, onlyoffice-cors"
> traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto: "https"
> traefik.http.middlewares.onlyoffice-cors.headers.accessControlAllowOrigin: "*"
> ```

That's working for me, too. Thank you so much! 

My docker-compose config:
```
version: '3'

services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${LOCAL_CONF_DIR}/onlyoffice:/var/log/onlyoffice
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HOSTNAME}-http.entrypoints=web"
      - "traefik.http.routers.${HOSTNAME}-http.rule=Host(`${HOSTNAME}.${DOMAIN0}`)"
      - "traefik.http.routers.${HOSTNAME}-http.middlewares=https_redirect@file"
      - "traefik.http.routers.${HOSTNAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${HOSTNAME}-https.rule=Host(`${HOSTNAME}.${DOMAIN0}`)"
      - "traefik.http.routers.${HOSTNAME}-https.tls=true"
      - "traefik.http.routers.${HOSTNAME}-https.middlewares=sts@file,onlyoffice-headers"
      - "traefik.http.services.${HOSTNAME}.loadbalancer.server.port=80"

      ## Middleware definition
      # Headers for onlyoffice, https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/151
      - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowOrigin=*"

networks:
  default:
    external:
      name: ${NETWORK}
```

**Comment by derdrave** [comment]
does work for me too. thanks to @calvinbui and also to @wcdgit for the full docker-compose for checkup-purposes!

**Comment by leonfc** [comment]
@calvinbui 's labels fixed it for me, too. Thanks a lot! Can we somehow add a note or full example to https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx to save people's time? The Traefik sample is still for version 1

**Comment by kungknut** [comment]
I can also confirm that adding the X-Forwarded-Proto header solved my issues.

**Comment by SuperSandro2000** [comment]
I can confirm that only the ``X-Forwarded-Proto`` Header is needed.

**Comment by 0x9060** [comment]
> > Similarly if you're having CORS problems, use the CORS header as well
> > ```yaml
> > traefik.http.routers.onlyoffice-secure.middlewares: "onlyoffice-sslheaders, onlyoffice-cors"
> > traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto: "https"
> > traefik.http.middlewares.onlyoffice-cors.headers.accessControlAllowOrigin: "*"
> > ```
> 
> That's working for me, too. Thank you so much!
> 
> My docker-compose config:
> 
> ```
> version: '3'
> 
> services:
>   onlyoffice:
>     container_name: onlyoffice
>     image: onlyoffice/documentserver:latest
>     restart: unless-stopped
>     stdin_open: true
>     tty: true
>     volumes:
>       - ${LOCAL_CONF_DIR}/onlyoffice:/var/log/onlyoffice
>     environment:
>       JWT_ENABLED: "true"
>       JWT_SECRET: ${SECRET}
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.${HOSTNAME}-http.entrypoints=web"
>       - "traefik.http.routers.${HOSTNAME}-http.rule=Host(`${HOSTNAME}.${DOMAIN0}`)"
>       - "traefik.http.routers.${HOSTNAME}-http.middlewares=https_redirect@file"
>       - "traefik.http.routers.${HOSTNAME}-https.entrypoints=websecure"
>       - "traefik.http.routers.${HOSTNAME}-https.rule=Host(`${HOSTNAME}.${DOMAIN0}`)"
>       - "traefik.http.routers.${HOSTNAME}-https.tls=true"
>       - "traefik.http.routers.${HOSTNAME}-https.middlewares=sts@file,onlyoffice-headers"
>       - "traefik.http.services.${HOSTNAME}.loadbalancer.server.port=80"
> 
>       ## Middleware definition
>       # Headers for onlyoffice, https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/151
>       - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
>       - "traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowOrigin=*"
> 
> networks:
>   default:
>     external:
>       name: ${NETWORK}
> ```

This config is not working for me... I'm still getting `(Connection refused) while connecting to upstream,`

**Comment by jcgruenhage** [comment]
So, I've digged a bit, and the (merged) PR to traefik that @SuperSandro2000 linked above does not fix it. I refactored the code in traefik again to make it a bit clearer what's actually happening, but it doesn't make a difference really.

This needs to be fixed in ONLYOFFICE, but this is not the appropriate repository for that issue. Will open one though.

**Comment by zilexa** [comment]
For future reference, none of the workaround examples above are actually complete or are correct. After a few hours of trial and error, this is how I got it working. 
I spend DAYS figuring this out as I am a Traefik and OO noob. And this Traefik forum topic send me searching in the dark wasting even more time: https://community.traefik.io/t/traefik-2-0-and-onlyoffice-not-work-work-correctly-in-v-2/3286

After I had http**s**://office.mydomain working, I tested the example doc file. When that worked, I started removing several Traefik labels until I got the bare minimum set of extra rules necessary to run OnlyOffice successfully with Traefikv2.0.

```
##_____________________ OnlyOffice Document Server [Cloud/Office]
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    depends_on:
      - onlyoffice-rabbitmq
    stdin_open: true
    restart: always
    tty: true
    ports:
      - "8889:80"
    volumes:
      - $USERDIR/docker/onlyoffice/data:/var/www/onlyoffice/Data
      - $USERDIR/docker/onlyoffice/log:/var/log/onlyoffice
      - $USERDIR/docker/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - $USERDIR/docker/onlyoffice/example:/var/www/onlyoffice/documentserver-example/public/files
      - $USERDIR/docker/onlyoffice/fonts:/usr/share/fonts
    dns: 1.1.1.1
    environment:
      - JWT_ENABLED="true"
      - JWT_SECRET=$ONLYOFFICEJWT
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
    labels:
     ## My standard traefikv2.0 labels for services exposed online:
      - traefik.enable=true
      - traefik.http.routers.office-redirect.entrypoints=web
      - traefik.http.routers.office-redirect.rule=Host(`office.$DOMAIN`)
      - traefik.http.middlewares.office-redirect.redirectscheme.scheme=https
      - traefik.http.routers.office.middlewares=office-redirect
      - traefik.http.routers.office-secure.entrypoints=websecure
      - traefik.http.routers.office-secure.rule=Host(`office.$DOMAIN`)
      - traefik.http.routers.office.tls.certresolver=letsencrypt
      - traefik.http.services.office.loadbalancer.server.port=80
      ## Extra labels for onlyoffice:
      - traefik.http.routers.office-secure.tls=true
      - traefik.http.routers.office-secure.middlewares=secure-headers
      - traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOrigin=*
      - traefik.http.routers.office.middlewares=secure-headers,cors-headers
      ## tested extra labels, works fine without DO NOT USE
      #- traefik.http.middlewares.office-redirectregex.redirectregex.regex=^http://(.*)
      #- traefik.http.middlewares.office-redirectregex.redirectregex.replacement=https://$$1
      #- traefik.http.middlewares.secure-headers.headers.referrerPolicy=no-referrer
      #- traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000
      #- traefik.http.middlewares.secure-headers.headers.forceSTSHeader=true
      #- traefik.http.middlewares.secure-headers.headers.stsPreload=true
      #- traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true
      #- traefik.http.middlewares.secure-headers.headers.browserXssFilter=true
```
Also: 
I accidentally removed my postgreSQL container, discovered OnlyOffice still worked without it !? 
Not sure how, but now OnlyOffice runs, just with rabbitmq as additional container. Perhaps the onlyoffice/documentserver image already contains a sql database: 
```
##____________________ Onlyoffice rabbitmq [CLOUD/Office]
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
```

**Comment by chmanie** [comment]
@wcdgit and @calvinbui thanks so much for sharing your configs! Sadly these are still not working for me. This is my current config:

```
  onlyoffice-document-server:
    container_name: nextcloud-onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - "traefik.http.routers.onlyoffice-document-server-http.entrypoints=web"
      - "traefik.http.routers.onlyoffice-document-server-http.rule=Host(`-SNIP-`)"
      - "traefik.http.routers.onlyoffice-document-server-http.middlewares=https_redirect@file"
      - "traefik.http.routers.onlyoffice-document-server-https.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice-document-server-https.rule=Host(`-SNIP-`)"
      - "traefik.http.routers.onlyoffice-document-server-https.tls=true"
      - "traefik.http.routers.onlyoffice-document-server-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.onlyoffice-document-server-https.middlewares=onlyoffice-sslheaders, onlyoffice-cors"
      - "traefik.http.services.onlyoffice-document-server.loadbalancer.server.port=80"
      - traefik.http.middlewares.onlyoffice-sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.onlyoffice-cors.headers.accessControlAllowOrigin=*
      - traefik.docker.network=traefik_default
```

Am I missing anything?

Also, I can't reach the document server on this domain (in the `Host`  rules), should that be possible?
