### ISSUE TITLE
Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by K73SK** [ONLYOFFICE/onlyoffice-nextcloud#152]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have tried to follow every solution I can find out there for this and for some reason, Nextcloud does _not_ want to connect to my docker image of OnlyOffice. I can connect to it in a browser and can even do a curl call to it through the container with my nextcloud instance (returns a 302 redirect page). But once I try to input the address in the settings, it just gives me the error "Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

I've setup my own network settings on the docker-compose.yml so that it can share the same network and I can just reference it by IP in the nextcloud instance. I did add the respective IP as a trusted domain and made sure to set the verify_peer_off to true. Here's the section of the docker-compose which contains the onlyoffice setup (yes, as you can see, I went as far as assigning an IP to every single thing just to troubleshoot):

```
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    build: ./onlyoffice
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - BALANCE=uri depth 3
      #- EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      # Uncomment the string below to redirect HTTP request to HTTPS request.
      # - FORCE_SSL=true
    stdin_open: true
    restart: always
    networks:
      nextnet:
        ipv4_address: 172.25.0.7
    expose:
     - '80'
     - '443'

  onlyoffice-haproxy:
    container_name: onlyoffice-haproxy
    image: dockercloud/haproxy:1.5.1
    depends_on:
      - onlyoffice-documentserver
    environment:
      - MODE=http
      # Uncomment the string below to specify the path of ssl certificates
      - CERT_FOLDER=/var/www/onlyoffice/Data/certs/
    stdin_open: true
    tty: true
    links:
     - onlyoffice-documentserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the string below to map a ssl certificate from host
      # to the proxy container
      - ./onlyoffice/DocumentServer/data/certs/onlyoffice.pem:/var/www/onlyoffice/Data/certs/onlyoffice.pem
    restart: always
    networks:
      nextnet:
        ipv4_address: 172.25.0.8
    ports:
      - '80:80'
      - '443:443'
       
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
      nextnet:
        ipv4_address: 172.25.0.9
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
      nextnet:
        ipv4_address: 172.25.0.10
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
    networks:
      nextnet:
        ipv4_address: 172.25.0.11
    restart: always
    expose:
      - '5432'
    volumes:
      - postgresql_data:/var/lib/postgresql

volumes:
  db:
  nextcloud:
  postgresql_data:

networks:
  nextnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
```

For the `build` Dockerfile I'm creating for the documentserver:
```
FROM onlyoffice/documentserver:latest
RUN sed -i -e 's/"rejectUnauthorized": true/"rejectUnauthorized": false/' /etc/onlyoffice/documentserver/default.json
RUN supervisorctl restart all
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

When I reach to https://172.25.0.8 in the browser, it shows correctly and even says "Document Server is running". If I do https://172.25.0.8/healtcheck it shows `true`. Go to the Nextcloud container, it fails.

**What is the expected behavior?**
No errors and I can use OnlyOffice in Nextcloud

**Did this work in previous versions of DocumentServer?**
N/A

**DocumentServer Docker tag:**
`onlyoffice/documentserver:latest`

**Host Operating System:**
Gentoo Linux
