### ISSUE TITLE
Unknown Error on document load

### ISSUE THREAD

**Issue by UbioZur** [ONLYOFFICE/onlyoffice-nextcloud#486]
Hi, 
I am a bit lost. It is a very common error, I can find a lot of post online with people having it, and many differents solutions, none of wich make sense or works for me. (I may need an explanation like if I am a baby ^^)

The error I have is the same as this one:
https://www.linuxbabe.com/wp-content/uploads/2017/11/onlyoffice-download-failed.webp
docker log:
```
Error: Error response: statusCode:308; headers:{"location":"https://nextcloud.mydomain.com/apps/onlyoffice/track?doc=MASSIVEUID","date":"Tue, 15 Jun 2021 05:22:38 GMT","content-length":"18","content-type":"text/plain; charset=utf-8"}; body:
,
Error: Error response: statusCode:308; headers:{"location":"https://nextcloud.mydomain.com/apps/onlyoffice/track?doc=MASSIVEUID","date":"Tue, 15 Jun 2021 05:32:39 GMT","content-length":"18","content-type":"text/plain; charset=utf-8"}; body:
,
[2021-06-15T05:32:39.467] [ERROR] nodeJS - postData error: docId = 2926400966;url = http://nextcloud.mydomain.com/apps/onlyoffice/track?doc=MASSIVEUID;data = {"key":"KEYUID","status":1,"users":["MYUSER"],"actions":[{"type":1,"userid":"MYUSER"}]}
```

I have all my containers behind a a reverse proxy (traefik), that automatically redirect the port 80 to port 443 and I have a wildcard SSL certificate for the whole server.

Next cloud works fine.

In order for nextcloud and onlyoffice to connect, I have to use for the Document Editing Service address
https://onlyoffice.mydomain.com (Disable Certificate Verification on or off doesn't change the error)
Any local IP or domain names (like just the container name, setup in my DNS) will not work.
Using http instead of https mean that when i try to open a document, I have an error saying that OnlyOffice cannot be reached.

If I try to use the demo server. I only have the 'document could not be saved' message when opening it.

only offce docker-compose.yml
```
# Only Office
    onlyoffice:
        container_name: onlyoffice
        image: "onlyoffice/documentserver"
        restart: unless-stopped
        networks: 
            proxy:
                ipv4_address: FIXIP
        dns:
            - DNSIP
        hostname: onlyoffice
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${HOME}/onlyoffice/logs:/var/log/onlyoffice
            - ${HOME}/onlyoffice/data:/var/www/onlyoffice/Data
            - ${HOME}/onlyoffice/filecache:/var/lib/onlyoffice
        env_file:
            - .oo.env
        environment:
            - PUID=1000
            - PGID=1000
            - DB_TYPE=mysql
        labels:
            - traefik.enable=true
            - traefik.http.routers.onlyoffice.entrypoints=websecure
            - traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.mydomain.com`)
            - traefik.http.routers.onlyoffice.service=onlyoffice
            - traefik.http.services.onlyoffice.loadbalancer.server.port=80
```

Trafik entry points
```
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: mydnsprovider
        domains:
          - main: mydomain.com
            sans: 
              - "*.mydomain.com"
```

I know it has something to do with not having the ssl certificate for only office (although it should have my wildcard let'sencrypt one from traefik as long as I use the full URL that pass by let's encrypt). but I can't figure out where are the files to change, on which docker, etc... so any help would be welcome.
