### ISSUE TITLE
Healthcheck Request: 400 Bad Request

### ISSUE THREAD

**Issue by unicmyce** [ONLYOFFICE/onlyoffice-nextcloud#632]
literally having sameissue as #125 with the difference that when i access the healthcheck through browser i receive the same 400 Bad Request as when try to sync with nextcloud.

**Comment by SergeyKorneyev** [comment]
Hello,
That probably means that the Document Server is malfunctioning. Could you check if its core services (Docservice, Converter) and dependencies (RabbitMQ, PostgreSQL, Nginx) are working correctly?
If you need more precise information on how to do that, let me know the OS you've installed the Document Server on and the installation type you used.

**Comment by werty1st** [comment]
make sure to set a dns server for docker. this was the cause on my setup.

```yaml
  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    networks:
      - "web"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - document_data1:/var/www/onlyoffice/Data
      - document_log1:/var/log/onlyoffice
      - document_db1:/var/lib/postgresql
      - ./local.json:/etc/onlyoffice/documentserver/local.json
      - ./default.json:/etc/onlyoffice/documentserver/default.json
    labels:
      traefik.enable: "true"
      traefik.http.routers.office.rule: Host(`docs.homelab.eu`)
      traefik.http.services.office.loadbalancer.server.port: 80
      traefik.http.services.office.loadbalancer.server.scheme: http
      traefik.http.routers.office.entrypoints: websecure
      traefik.http.routers.office.tls.certresolver: myresolver
      traefik.http.routers.office.service: office
      #traefik.http.routers.office.middlewares: office-headers
      #traefik.http.middlewares.office-headers.headers.customrequestheaders.X-Forwarded-Proto: https
      #traefik.http.middlewares.office-headers.headers.accessControlAllowOrigin: "*"

  nextcloud:
    image: nextcloud
    links:
      - mysql:db
    volumes:
      - ./data/:/var/www/html/data/
      - ./nextcloud/:/var/www/html/
      - ./config/:/var/www/html/config/
      - /pool18tb/Downloads/:/Downloads
      - /pool18tb/Filme/:/media/Filme:ro
      - /pool18tb/Serien/:/media/Serien:ro
      - /pool18tb/Audio/:/media/Audio:ro
    restart: always
    user: "1000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
#    command: |
#      apt update && apt install smbclient libsmbclient-dev
#      pecl install smbclient
#      docker-php-ext-enable smbclient
    environment: 
      - APACHE_RUN_USER=#1000
    networks:
        - "web"
        - "mysql"
    labels:
      traefik.enable: "true"
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.homelab.eu`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.services.nextcloud.loadbalancer.server.scheme: http
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: myresolver

      ofelia.enabled: "true"
      ofelia.job-exec.nextcloud.schedule: "@hourly"
      ofelia.job-exec.nextcloud.user: "1000"
      ofelia.job-exec.nextcloud.command: "php -f /var/www/html/cron.php"
      ofelia.job-exec.nextcloud-files.schedule: "0 0 3 * * *"
      ofelia.job-exec.nextcloud-files.user: "1000"
      ofelia.job-exec.nextcloud-files.command: "php occ files:scan --all"
      ofelia.job-exec.nextcloud-db.schedule: "@daily"
      ofelia.job-exec.nextcloud-db.no-overlap: "true"
      ofelia.job-exec.nextcloud-db.user: "1000"
      ofelia.job-exec.nextcloud-db.command: "php occ db:add-missing-indices && php occ db:add-missing-primary-keys && php occ db:convert-filecache-bigint"

```
