### ISSUE TITLE
Error when trying to connect (Bad Request or timeout error)/Mixed Active Content is not allowed. HTTPS address for Document Server is required.

### ISSUE THREAD

**Issue by Ammar7347** [ONLYOFFICE/onlyoffice-nextcloud#81]
I've recently installed the document server on a fresh server running Ubuntu 16.04. I want to use the onlyoffice for my nextcloud instance which is hosted on a different server.  It works with both HTTP and https but unfortunately, even after installing the SSL certificate, it shows the red triangle (Not secured) sign in my browser. The thing is I don't even want to use HTTPS but it won't let me use HTTP as it says "Error when trying to connect (Mixed Active Content is not allowed. HTTPS address for Document Server is required.)". So, basically there is no option other than to use HTTPS but then I get "Error when trying to connect (Bad Request or timeout error)" even though it says document server is running even with HTTPS. 

I followed [this](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx) and I get `Error when trying to connect (Bad Request or timeout error)` . Moreover, `/var/log/onlyoffice/documentserver/nginx.error.log` is empty. And yes the document server is running just fine as you can see for your self at https://51.38.105.3/welcome/

Any help regarding this would be highly appreciated.

**Comment by zandercodes** [comment]
I have the same problem.

**Comment by zandercodes** [comment]
@Ammar7347 
I have a solution for this problem.
You need to activate JWT, then it doesn't matter if it's http or https.

![Bildschirmfoto 2019-07-22 um 14 07 58](https://user-images.githubusercontent.com/46308805/61631245-26ec5e80-ac8a-11e9-9b99-55c5e4792135.png)

You don't have an internal server, then you have to use the public IP or domain.
Don't forget to add the domain or IP in Nextcloud Config.

Best Regards
ZanderCodes

**Comment by frakman1** [comment]
Can you show how to accomlish this? "You need to activate JWT"

**Comment by zandercodes** [comment]
I've run the document server over dockers and there I've only set the env variables.

```
version: '3.5'

services:
  nexcloud-onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-onlyoffice
    restart: always
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/data
      - ./onlyoffice/log:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=<Here your own secret key>
```
